export const MOCK_MOVIES = [
  {
    id: 101,
    title: "Redemption",
    overview: "A powerful drama about hope, friendship, and freedom.",
    release_date: "1994-09-23",
    vote_average: 9.3,
    poster_path: "https://picsum.photos/seed/redemption/500/750",
    backdrop_path: "https://picsum.photos/seed/redemption-back/1200/700",
  },
  {
    id: 102,
    title: "Quantum Chase",
    overview: "A sci‑fi adventure through hidden worlds and time loops.",
    release_date: "2023-07-12",
    vote_average: 7.8,
    poster_path: "https://picsum.photos/seed/quantum/500/750",
    backdrop_path: "https://picsum.photos/seed/quantum-back/1200/700",
  },
  {
    id: 103,
    title: "Night Runner",
    overview: "A fast thriller set in a city that never sleeps.",
    release_date: "2021-11-05",
    vote_average: 8.1,
    poster_path: "https://picsum.photos/seed/nightrunner/500/750",
    backdrop_path: "https://picsum.photos/seed/nightrunner-back/1200/700",
  },
  {
    id: 104,
    title: "Laugh City",
    overview: "A comedy where everything goes wrong in the funniest way.",
    release_date: "2020-05-20",
    vote_average: 7.2,
    poster_path: "https://picsum.photos/seed/laughcity/500/750",
    backdrop_path: "https://picsum.photos/seed/laughcity-back/1200/700",
  },
  {
    id: 105,
    title: "Ocean Mystery",
    overview: "A detective story that starts with a message from the sea.",
    release_date: "2022-02-02",
    vote_average: 7.9,
    poster_path: "https://picsum.photos/seed/oceanmystery/500/750",
    backdrop_path: "https://picsum.photos/seed/oceanmystery-back/1200/700",
  },
];